FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive 

RUN apt-get update && apt-get install -y python3-dev python3-pip libcurl4-openssl-dev python3-dev libssl-dev
RUN python3 -m pip install requests pycurl

WORKDIR /opt/albatar
ENTRYPOINT ["python3"]
